apiVersion: v1
kind: Service
metadata:
  name: ttyd-k9s
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ttyd-k9s
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 7681
      protocol: TCP
      name: http