deployment:
  replicaCount: 3
  resources:
    limits:
      cpu: 20m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 100Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/name: hello-kubernetes
ingress:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
  configured: true
  enabled: true
  extraPaths: ''
  hosts:
  - helloworld.maifuj.com
  ingressClassName: nginx
  issuer:
    name: letsencrypt-prod
    scope: cluster
  labels: {}
  path: /
  pathPrefix: ''
  pathType: Prefix
  rewritePath: false
  secretName: helloworld-secret
message: Hi Alam.
service:
  externalPort: 443
  port: 8080
  type: ClusterIP
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
