---
- hosts: k8s-master
  become: false
  vars:
    PROJECT_PATH: k8s_aws_lite  # File will be  created at home directory
    KUBERNETES_MAJOR_VERSION: v1.32
    KUBERNETES_VERSION: 1.32.2  # add 'v' in at prefix whenever required.
    PACKAGE_DIRECTORY: packages
    USER: ubuntu
    MASTER_NODE_IP: 172.31.0.37
    WORKER_NODE_IP: 172.31.0.38
  roles:
    - default-apps
