pipeline {
    parameters {
        string(name: 'GIT_REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws.git', description: 'Enter the git repo URL')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'main', description: 'Enter the branch name')
        string(name: 'APP_FOLDER_PATH', defaultValue: 'apps/ttyd-k9s', description: 'Folder containing the Dockerfile')
        string(name: 'APP_NAME', defaultValue: 'ttyd-k9s', description: 'App name')
        string(name: 'REGISTRY_ENDPOINT', defaultValue: 'harbor.maifuj.com/dev-apps/', description: 'Image registry endpoint')
    }
    agent {
        kubernetes {
            yaml '''
            kind: Pod
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                imagePullPolicy: IfNotPresent
                command:
                - sleep
                args:
                - 9999999
                volumeMounts:
                  - name: jenkins-docker-cfg
                    mountPath: /kaniko/.docker
              volumes:
              - name: jenkins-docker-cfg
                projected:
                  sources:
                  - secret:
                      name: docker-credentials
                      items:
                        - key: .dockerconfigjson
                          path: config.json
            '''
        }
    }

    stages {
        stage('Build and Push') {
            steps {
                container(name: 'kaniko',shell: '/busybox/sh') {
                  sh '''#!/busybox/sh
                  /kaniko/executor --context ${APP_FOLDER_PATH} --destination ${HREGISTRY_ENDPOINT}/${APP_NAME}:${BUILD_NUMBER}
                  '''
                }
            }
        }
    }
}

