pipeline {
    parameters {
        string(name: 'GIT_REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws_lite.git', description: 'Enter the git repo URL')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'master', description: 'Enter the branch name')
        string(name: 'APP_FOLDER_PATH', defaultValue: 'EvictedPodCleaner', description: 'Folder containing the Dockerfile')
        string(name: 'APP_NAME', defaultValue: 'evicted-pod-cleaner', description: 'App name')
        string(name: 'DOCKER_USER_NAME', defaultValue: 'skmaifujalam', description: 'Docker Hub Username')
    }
    agent {
        kubernetes {
            yaml '''
            kind: Pod
            spec:
              containers:
              - name: kaniko
                image: gcr.io/kaniko-project/executor:debug
                imagePullPolicy: IfNotPresent
                command:
                - sleep
                args:
                - 9999999
                volumeMounts:
                  - name: jenkins-docker-cfg
                    mountPath: /kaniko/.docker
              volumes:
              - name: jenkins-docker-cfg
                projected:
                  sources:
                  - secret:
                      name: docker-credentials
                      items:
                        - key: .dockerconfigjson
                          path: config.json
            '''
        }
    }

    stages {
        stage('Git Checkout') {
            steps {
                container(name: 'kaniko') {
                    checkout([$class: 'GitSCM',
                        branches: [[name: "${params.GIT_BRANCH_NAME}"]],
                        userRemoteConfigs: [[url: "${params.GIT_REPO_NAME}"]]
                    ])
                }
            }
        }
        stage('Build and Push') {
            steps {
                container(name: 'kaniko',shell: '/busybox/sh') {
                  sh '''#!/busybox/sh
                  /kaniko/executor --context ${APP_FOLDER_PATH} --destination ${DOCKER_USER_NAME}/${APP_NAME}:${BUILD_NUMBER}
                  '''
                }
            }
        }
    }

}
