#apiVersion: secrets.hashicorp.com/v1beta1
#kind: VaultConnection
#metadata:
#  name: vault-maifuj
#  namespace: vault-secrets-operator
#spec:
#  address: https://vault.maifuj.com
#  skipTLSVerify: false   # or true if you don’t have CA certs
#  caCertSecretRef:
#    name: vault-certificate-secret  # optional, if you have a CA cert in a Secret