apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuthGlobal
metadata:
  name: default
  namespace: vault-secrets-operator  # Its a namespace based,all namespace consume VSO need it.
spec:
  vaultConnectionRef: default    # Which connection to use (see VaultConnection CRD)
  defaultAuthMethod: kubernetes
  kubernetes:                    # Kubernetes auth method configuration
    role: vault-operator-readonly # The Vault role that this auth method will use
    serviceAccount: vault-secrets-operator
    mount: kubernetes             # Mount path of the auth method in Vault (default is "kubernetes")
    audiences:
      - vault                   # The expected audience for the JWT token (default is "vault")