apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hello-kubernetes-appset
  namespace: argo-cd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
   - matrix:
        generators:
          - git:
              repoURL: https://github.com/maifujalam/k8s_aws_lite.git
              revision: main
              files:
                - path: k8s/v1.36.2/clusters/*/helloworld/appset-config.yaml
          - clusters:
              selector:
                matchLabels:
                  cluster: '{{ index .path.segments 3}}'
  template:
    metadata:
      name: '{{ index .path.segments 4}}-{{ index .path.segments 3}}'
      labels:
        app: '{{ index .path.segments 4}}'
        cluster-name: '{{ index .path.segments 3}}'
    spec:
      project: dev-project
      sources:
        - repoURL: https://github.com/maifujalam/k8s_aws_lite.git
          targetRevision: '{{.chart_version}}'
          chart: '{{.chart_name}}'
          helm:
            valuesFiles:
              - $values/{{.path.path}}/helm-config.yaml
            skipCrds: true
        - repoURL: https://github.com/maifujalam/k8s_aws_lite.git
          targetRevision: main
          ref: values
      destination:
        server: '{{.server}}'
        namespace: '{{.namespace}}'