pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
metadata:
  namespace: jenkins
spec:
  containers:
  - name: jnlp
    image: harbor.maifuj.com/dev-apps/jnlp-agent:7
    imagePullPolicy: IfNotPresent
    env:
    - name: JENKINS_TUNNEL
      value: "jenkins-dev-agent.jenkins.svc.cluster.local:50000"
    - name: REMOTING_OPTS
      value: "-noReconnectAfter 1d"
    - name: JENKINS_AGENT_WORKDIR
      value: "/home/jenkins/agent"
    - name: JENKINS_URL
      value: "http://jenkins-dev.jenkins.svc.cluster.local:8080/"
    resources:
      limits:
        memory: "512Mi"
        cpu: "500m"
      requests:
        memory: "256Mi"
        cpu: "250m"
    volumeMounts:
    - mountPath: "/home/jenkins/agent"
      name: workspace-volume
    - name: jenkins-docker-cfg
      mountPath: /home/jenkins/.docker
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Never
  serviceAccountName: default
  volumes:
  - emptyDir: {}
    name: workspace-volume
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: docker-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
'''
        }
    }

    environment {
        HELM_VALUES_FILE = 'values.yaml'
        HELM_REPO_NAME   = "dev-apps"
        HELM_REPO        = "oci://harbor.maifuj.com/dev-apps"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Lint & Package Helm Chart') {
            steps {
                dir("${params.CHART_FOLDER_PATH}") {
                    sh "helm lint ."
                    sh "helm package ."
                }
            }
        }

        stage('Push Helm Chart') {
            steps {
                dir("${params.CHART_FOLDER_PATH}") {
                    script {
                        def chartFile = sh(script: "ls -t *.tgz | head -n 1", returnStdout: true).trim()
                        echo "Pushing chart: ${chartFile}"
                        sh """
                          export HELM_EXPERIMENTAL_OCI=1
                          HELM_REGISTRY_CONFIG=/home/jenkins/.docker/config.json
                          helm push --force ${chartFile} ${HELM_REPO}
                        """
                    }
                }
            }
        }
    }
    post {
        success { echo "✅ Helm chart pushed successfully" }
        failure { echo "❌ Pipeline failed" }
    }
}
