pipeline {
    agent {
        kubernetes {
            yaml '''
            apiVersion: "v1"
            kind: "Pod"
            metadata:
              labels:
                jenkins/jenkins-jenkins-agent: "true"
                jenkins/label: "jenkins-jenkins-agent"
                kubernetes.jenkins.io/controller: "http___jenkins_jenkins_svc_cluster_local_8080x"
              namespace: "jenkins"
            spec:
              containers:
              - args:
                env:
                - name: "JENKINS_TUNNEL"
                  value: "jenkins-dev-agent.jenkins.svc.cluster.local:50000"
                - name: "REMOTING_OPTS"
                  value: "-noReconnectAfter 1d"
                - name: "JENKINS_AGENT_WORKDIR"
                  value: "/home/jenkins/agent"
                - name: "JENKINS_URL"
                  value: "http://jenkins-dev.jenkins.svc.cluster.local:8080/"
                image: "harbor.maifuj.com/dev-apps/jnlp-agent:7"
                imagePullPolicy: "IfNotPresent"
                name: "jnlp"
                resources:
                  limits:
                    memory: "512Mi"
                    cpu: "500m"
                  requests:
                    memory: "256Mi"
                    cpu: "250m"
                tty: false
                volumeMounts:
                - mountPath: "/home/jenkins/agent"
                  name: "workspace-volume"
                  readOnly: false
                - name: jenkins-docker-cfg
                  mountPath: /home/jenkins/.docker
                workingDir: "/home/jenkins/agent"
              nodeSelector:
                kubernetes.io/os: "linux"
              restartPolicy: "Never"
              serviceAccountName: "default"
              volumes:
              - emptyDir:
                  medium: ""
                name: "workspace-volume"
              - name: jenkins-docker-cfg
                projected:
                  sources:
                  - secret:
                      name: docker-credentials
                      items:
                        - key: .dockerconfigjson
                          path: config.json
            '''
        }
    }
    environment {
        HELM_VALUES_FILE = 'values.yaml'
        HELM_REPO_NAME="dev-apps"
    }
    parameters {
        string(name: 'GIT_REPO_NAME', defaultValue: 'https://github.com/maifujalam/k8s_aws_lite.git', description: 'Enter the git remote name')
        string(name: 'GIT_BRANCH_NAME', defaultValue: 'main', description: 'Enter the branch name to pull from')
        string(name: 'CHART_FOLDER_PATH', defaultValue: 'k8s/v1.36.2/manifests/ttyd-k9s/', description: 'Enter the folder path name which to be helm build')
        string(name: 'HELM_REPO', defaultValue: 'oci://harbor.maifuj.com/dev-apps', description: 'Enter the helm remote name,where to push')
    }
    stages {
        stage('Git Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: "${params.GIT_BRANCH_NAME}"]],
                    userRemoteConfigs: [[url: "${params.GIT_REPO_NAME}"]]
                ])
            }
        }
        stage('Render Helm Chart') {
            steps {
                script {
                    dir("${params.CHART_FOLDER_PATH}") {
                        echo "Folder to render: ${params.CHART_FOLDER_PATH}";
                        def output = sh(script: 'pwd;helm version;ls' , returnStdout: true).trim()
                        echo "Output: ${output}"
                        try {
                            // Run helm template command
                            def template_output = sh(script: 'helm template . -f ${HELM_VALUES_FILE}', returnStdout: true).trim()
                            echo "Helm template output:\n${template_output}"
                            echo "\n\nHelm template validation passed.\n"
                        } catch (Exception e) {
                            error("Helm template validation failed: ${e}")
                        }
                    }
                }
            }
        }

        stage('Build Helm Chart') {
            steps {
                script {
                    // Build and package the Helm chart
                    dir("${params.CHART_FOLDER_PATH}") {
                        echo "Folder to build: ${params.CHART_FOLDER_PATH}";
                        try {
                            // Run helm template command
                            def lint_output = sh(script: 'helm lint .', returnStdout: true).trim()
                            echo "Helm lint output:\n${lint_output}"
                            echo "\n\nHelm lint successful.\n"
                        } catch (Exception e) {
                            error("Helm lint failed: ${e}")
                        }
                        try {
                            // Run helm template command
                            def package_output = sh(script: 'helm package .', returnStdout: true).trim()
                            echo "Helm package output:\n${package_output}"
                            echo "\n\nHelm package successful.\n"
                        } catch (Exception e) {
                            error("Helm package failed: ${e}")
                        }
                    }
                }
            }
        }

        stage('Push Helm Chart') {
            steps {
              script {
                def chartFile = sh(script: "ls -t *.tgz | head -n 1", returnStdout: true).trim()
                echo "Pushing chart: ${chartFile}"
                sh """
                  export HELM_EXPERIMENTAL_OCI=1
                  # Helm will reuse docker config mounted at /home/jenkins/.docker/config.json
                  HELM_REGISTRY_CONFIG=/home/jenkins/.docker/config.json \
                  helm push --force ${chartFile} ${params.HELM_REPO}
                """
              }
            }
        }
    }

    post {
        always {
            echo "Pipeline finished"
        }
        failure {
            echo "Pipeline failed"
        }
        success {
            echo "Helm chart build successful"
        }
    }
}
