- name: Check if calico already installed
  shell: helm list -A | grep calico
  register: r2
  ignore_errors: true

- name: Add helm chart repos
  shell: |
    helm repo add projectcalico https://docs.tigera.io/calico/charts;
    helm repo add cert-manager https://charts.jetstack.io;
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx;
    helm repo add argo https://argoproj.github.io/argo-helm;
    helm repo update;
  ignore_errors: true

- name: Clone repo
  shell: cd;rm -rfv {{PROJECT_PATH}}; git clone https://github.com/maifujalam/{{PROJECT_PATH}}.git
  ignore_errors: true

- name: Install calico tigera CIDRs
  shell: helm template calico-crds projectcalico/crd.projectcalico.org.v1 --version v3.32.1 | kubectl apply --server-side -f -

- name: Install calico
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    create_namespace: true
    chart_version: v3.32.1
  when: r2.rc != 0

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: cert-manager/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    chart_version: v1.21.0
    values_files:
      - /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/values.yaml
    values:
      global:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"

- name: Install self signed certs
  shell: kubectl apply -f /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/self-sign-issuer.yaml

- name: debug vault
  debug:
    msg: "ADMIN_PASSWORD={{ ADMIN_PASSWORD }}"

- name: Recreate route53-credentials-secret
  kubernetes.core.k8s:
    state: present
    namespace: cert-manager
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: route53-credentials-secret
      type: Opaque
      stringData:
        access-key-id: "{{ ACCESS_KEY_ID }}"
        secret-access-key: "{{ SECRET_ACCESS_KEY }}"

- name: Copy the cluster issuer template
  template:
    src: templates/prod-cluster-issuer-llt.yaml.j2
    dest: /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/prod-cluster-issuer-llt.yaml

- name: Copy the wildcard certificate template
  template:
    src: templates/wildcard-certificate.yaml.j2
    dest: /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/wildcard-certificate.yaml

- name: Kubernertes create cluster issuer
  shell: kubectl apply -f /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/prod-cluster-issuer-llt.yaml

- name: Kubernertes create wildcard certificate
  shell: kubectl apply -f /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/wildcard-certificate.yaml

- name: Check if ingress-nginx already installed
  shell: helm list -A | grep ingress-nginx
  register: r4
  ignore_errors: true

- name: Install ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    chart_version: 4.15.1
    values:
      controller:
        nodeSelector:
          kubernetes.io/hostname: master
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        service:
          type: NodePort
          nodePorts:
            http: 32080
            https: 32443
#         extraArgs:
#           tcp-services-configmap: "ingress-nginx/tcp-services"


- name: Install argo-cd
  kubernetes.core.helm:
    name: argo-cd
    chart_ref: argo/argo-cd
    release_namespace: argo-cd
    create_namespace: true
    chart_version: 10.1.3
    values:
      installCRDs: true
      global:
        domain: argocd.maifuj.com
      configs:
        params:
          server.insecure: true
        secret:
          argocdServerAdminPassword: "{{ ARGOCD_ADMIN_PASSWORD_HASH }}"
      controller:
        service:
          type: NodePort
          nodePorts:
            http: 32080
            https: 32443
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
      dex:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/hostname: master
      redis:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/hostname: master
      repoServer:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/hostname: master
      server:
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        nodeSelector:
          kubernetes.io/hostname: master


- name: Make default ssl backend
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    chart_version: 4.15.1
    values:
      controller:
        extraArgs:
          default-ssl-certificate: "cert-manager/wildcard-certificate-secret-prod"

- name: Copy kubeconfig file
  shell: cp -v ~/.kube/config {{KUBECONFIG_PATH}}

- name: Update kubeconfig with MASTER_IP
  ansible.builtin.replace:
    path: "{{ KUBECONFIG_PATH }}"
    regexp: 'https://master:6443'
    replace: "https://{{ MASTER_NODE_IP }}:6443"

- name: ArgoCD login
  shell: "argocd login argocd.maifuj.com --username admin --password {{ ADMIN_PASSWORD }} --insecure"


- name: Add argocd node to the cluster
  shell: argocd cluster add kubernetes-admin@local-k8s --upsert --insecure --yes --label cluster-name=dev --name dev --kubeconfig ~/config  --grpc-web

- name: Install Default Apps
  shell: kubectl apply -f /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/bootstrap/
