- name: Check if calico already installed
  shell: helm list -A | grep calico
  register: r2
  ignore_errors: true

- name: Add helm chart repos
  shell: |
    helm repo add projectcalico https://docs.tigera.io/calico/charts;
    helm repo add cert-manager https://charts.jetstack.io;
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx;
    helm repo add argo https://argoproj.github.io/argo-helm;
    helm repo update;
  ignore_errors: true

- name: Clone repo
  shell: cd;rm -rfv {{PROJECT_PATH}}; git clone https://github.com/maifujalam/{{PROJECT_PATH}}.git
  ignore_errors: true

- name: Install calico tigera CIDRs
  shell: helm template calico-crds projectcalico/crd.projectcalico.org.v1 --version v3.32.1 | kubectl apply --server-side -f -

- name: Install calico
  kubernetes.core.helm:
    name: calico
    chart_ref: projectcalico/tigera-operator
    release_namespace: tigera-operator
    create_namespace: true
    chart_version: v3.32.1
#     values_files:
#       - /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/tigera-operator/values.yaml
  when: r2.rc != 0

- name: Check if cert-manager already installed
  shell: helm list -A | grep cert-manager
  register: r3
  ignore_errors: true

- name: Install cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_ref: cert-manager/cert-manager
    release_namespace: cert-manager
    create_namespace: true
    chart_version: v1.21.0
    values_files:
      - /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/values.yaml
    values:
      global:
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
  when: r3.rc != 0

- name: Install self signed certs
  shell: kubectl apply -f /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/cert-manager/self-sign-issuer.yaml
  when: r3.rc != 0

- name: Check if ingress-nginx already installed
  shell: helm list -A | grep ingress-nginx
  register: r4
  ignore_errors: true

- name: Install ingress-nginx
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    release_namespace: ingress-nginx
    create_namespace: true
    chart_version: 4.15.1
    values:
      controller:
        nodeSelector:
          kubernetes.io/hostname: master
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
        service:
          type: NodePort
          nodePorts:
            http: 32080
            https: 32443
#         extraArgs:
#           tcp-services-configmap: "ingress-nginx/tcp-services"
  when: r4.rc != 0

- name: Sleep for 30 sec
  shell: sleep 30;
  when: r4.rc != 0

# - name: Check if argo-cd already installed
#   shell: helm list -A | grep argo-cd
#   register: r5
#   ignore_errors: true
- name: Copy argocd helm chart from local
  copy:
    src:  argo-cd-10.1.4.tgz
    dest: /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/argo-cd-10.1.4.tgz

- name: Install argo-cd
  kubernetes.core.helm:
    name: argo-cd
    chart_ref: /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/argo-cd-10.1.4.tgz
    release_namespace: argo-cd
    create_namespace: true
    chart_version: 10.1.4
    values:
      installCRDs: true
      configs:
        params:
          server.insecure: true
      server:
        config:
          url: https://argocd.maifuj.com
        ingress:
          enabled: true
          https: false
          ingressClassName: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
          hosts:
            - argocd.maifuj.com
          service:
            ports:
              http: 80
        tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"

- name: Install Default Apps
  shell: kubectl apply -f /home/{{USER}}/{{PROJECT_PATH}}/k8s/{{KUBERNETES_VERSION}}/manifests/default-applications.yaml
