kind: List
metadata:
  name: grafana
  namespace: grafana
apiVersion: v1
items:
- apiVersion: grafana.integreatly.org/v1beta1
  kind: Grafana
  metadata:
    annotations:
    labels:
      dashboards: grafana
    name: grafana
    namespace: grafana
  spec:
    client:
      timeout: 5
    config:
      analytics:
        check_for_updates: "false"
        reporting_enabled: "false"
      auth:
        disable_login_form: "false"
      log:
        mode: console
      security:
        admin_password: vault:secrets/data/dev/grafana/default#password
        admin_user: vault:secrets/data/dev/grafana/default#user
        disable_gravatar: "false"
    deployment:
      spec:
        replicas: 1
        strategy:
          type: Recreate
        template:
          metadata:
            annotations:
              vault.security.banzaicloud.io/vault-addr: https://vault-dev.vault.svc.cluster.local:8200
              vault.security.banzaicloud.io/vault-role: grafana-readonly
              vault.security.banzaicloud.io/vault-path: kubernetes
              vault.security.banzaicloud.io/vault-skip-verify: "true"
              vault.security.banzaicloud.io/vault-env: "true"
          spec:
            containers:
            - name: grafana
              securityContext:
                readOnlyRootFilesystem: false
    ingress:
      spec:
        ingressClassName: nginx
        rules:
        - host: grafana.maifuj.com
          http:
            paths:
            - backend:
                service:
                  name: grafana-service
                  port:
                    number: 3000
              path: /
              pathType: Prefix
    version: 13.0.1
