controller:
  JCasC:
    configScripts:
      jenkinscasc: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.
          jobs:
            - script: >
              job('example1') {
                steps {
                  batchFile('echo Hello World1!')
                }
              }