controller:
  JCasC:
    configScripts:
      jenkinscasc: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.
        jobs:
        - script: >
          pipelineJob('seed-job') {
            description('Seed job that loads Job DSL scripts from Git.')
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/maifujalam/k8s_aws_lite.git')
                    }
                    branches('*/main')
                  }
                  scriptPath('jenkins/seed_main/jobs.groovy') # path inside repo
                }
              }
            }
          }