controller:
  JCasC:
    configScripts:
      jenkinscasc: |
        jenkins:
          systemMessage: Welcome to our CI\CD server.
          jobs:
             - file: /var/jenkins_home/jenkins/ci/Jenkinsfile