region                = "ap-south-1"
name                  = "launch-template-rhel"
delete_on_termination = "true"
instance_type         = "t2.micro"
os                    = "rhel9"
key_name              = "id_rsa"
