---
# Source: vault/templates/prometheus-servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-name-vault
  labels:
    helm.sh/chart: vault-0.28.1
    app.kubernetes.io/name: vault
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      app.kubernetes.io/instance: release-name
      vault-active: "true"
  endpoints:
  - port: http
    interval: 30s
    scrapeTimeout: 10s
    scheme: http
    path: /v1/sys/metrics
    params:
      format:
      - prometheus
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames:
      - default
